### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [2]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [3]:
a = torch.tensor(2)
a

tensor(2)

In [4]:
b = torch.tensor(3)
a * b

tensor(6)

### Convert a tensor to scalar

In [5]:
c= b.item()
c

3

### Creating 2D tensor

In [6]:
A = torch.tensor([[1,2],[5,6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [7]:
B = A.numpy()
B

array([[1, 2],
       [5, 6]])

### Convert from numpy array to tensor

In [8]:
C = torch.from_numpy(B)
C

tensor([[1, 2],
        [5, 6]])

## PyTorch and GPU

check if GPU is available

In [9]:
torch.cuda.is_available()

True

In [10]:
C.device

device(type='cpu')

In [11]:
D = C.cuda()
D

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [12]:
D.device

device(type='cuda', index=0)

In [13]:
# C + D

## Basic operations

In [14]:
# D.numpy()

E = D.cpu().numpy()
E

array([[1, 2],
       [5, 6]])

In [15]:
D * 2

tensor([[ 2,  4],
        [10, 12]], device='cuda:0')

In [16]:
D - 2

tensor([[-1,  0],
        [ 3,  4]], device='cuda:0')

In [17]:
D.cpu() * np.array([1,2])

/tmp/ipython-input-1707415638.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array([1,2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [18]:
A = torch.tensor([[4,5],[8,9]])
B = torch.tensor([[1,4],[7,8]])

torch.matmul(A,B)

tensor([[ 39,  56],
        [ 71, 104]])

In [19]:
torch.mm(A,B)

tensor([[ 39,  56],
        [ 71, 104]])

In [20]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [21]:
A

tensor([[4, 5],
        [8, 9]])

In [22]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [23]:
a = torch.zeros(1,2,3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [24]:
b = torch.ones(1,2,3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [25]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [26]:
R1 = torch.rand(2,3)
R1

tensor([[0.0278, 0.8717, 0.4996],
        [0.4311, 0.1069, 0.4267]])

In [27]:
R2 = torch.randn(2,3)
R2

tensor([[ 0.0624,  0.3675,  0.5279],
        [ 2.8508, -1.5222, -0.9366]])

In [28]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

### Checking the shape of a tensor

In [29]:
A.shape

torch.Size([2, 2])

In [30]:
A.size()

torch.Size([2, 2])

### Changing the shape of a tensor

In [31]:
u = torch.arange(6)
u.shape

torch.Size([6])

In [32]:
v = u.reshape(2,3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [33]:
w = u.view(3,2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [34]:
a =  torch.arange(4)
b =  torch.arange(4) + 1

c = torch.stack([a,b], axis=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [35]:
d = torch.stack([a,b],axis = 1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [36]:
# concatenate
e =torch.cat([a,b], axis=0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

### Squeezing a tensor (removing an extra dimension)

In [37]:
A = torch.zeros((1,2,3))
B= A.squeeze()
B

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [38]:
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [39]:
# H.shape = (6, )
C = B.unsqueeze(axis=0)
C.size()

torch.Size([1, 2, 3])

In [40]:
C.shape

torch.Size([1, 2, 3])

## Indexing

In [41]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [42]:
P[[0,1,2],[0,1,2]]
P[0:3,0:3]

tensor([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [43]:
torch.inverse(torch.tensor([[2.0,0.0],[0.0,5.0]]))

tensor([[0.5000, 0.0000],
        [0.0000, 0.2000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [44]:
A **2

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [45]:
A.sum()

tensor(0.)

In [46]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [47]:
X =torch.randn(200, 7)
b =torch.randn(8, 1)
e =torch.randn(200, 1)

In [48]:
on = torch.ones(200,1)


In [49]:
X = torch.cat((on,X), dim=1)

In [50]:
y = X@b + e

In [51]:
ins = X.t() @ X
b_hat = torch.inverse(ins)@X.t() @y

In [52]:
y_hat = X@b_hat

$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [53]:
y_np = y.cpu().numpy()
y_hat_np = y_hat.cpu().numpy()



In [54]:
sd = np.mean((y_np - y_hat_np)**2)

In [56]:
MSE =  1/200*sd
print('calculate-MSE:',MSE)

calculate-MSE: 0.0046176994
